"""empty message

Revision ID: 3a9b959def5f
Revises: 330168ea7ae4
Create Date: 2023-11-09 02:05:45.479204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9b959def5f'
down_revision = '330168ea7ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=False))
        batch_op.drop_column('nventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nventory_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
